#driver=com.mysql.cj.jdbc.Driver
#url=jdbc:mysql://127.0.0.1:3306/scoula_db
jdbc.driver=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
jdbc.url=jdbc:log4jdbc:mysql://localhost:3306/scoula_db
jdbc.username=scoula
jdbc.password=1234

## weather api setting
weather.url=http://api.openweathermap.org/data/2.5/weather
weather.api_key=da8699a53c99f1ac2aab47f759c4b3da
weather.icon_url=http://openweathermap.org/img/w/%s.png
